### ISSUE TITLE
Batch image problem

### ISSUE THREAD

**Issue by charliebrown777** [Satellile/yara#2]
Hello, I am using your yara app for ComfyUI. Quite useful for me. Thank you!
I have a question here. I generate a batch of images in low resolution, which in the workflow there is a high-res sampler was turning off. I will pick some from the results and turn on the high-res sampler and generate again. Is there any method I can put all these pngs into a folder, extract all the metadata, turn on the highres-sampler (Ctrl+M), and combine it into a json file and load it in your yara? In this way I can save tons of time putting them in comfy one by one. Thanks!

Message also sent on Reddit.

**Comment by Satellile** [comment]
Glad to hear my tool has been of use!

I like this idea, I have a similar workflow. I went a bit overboard with the caffeine today and spent 13+ hours implementing it lol. It's working, but I still need to fully finish it, add a few more features, and test it at least a little bit. Hopefully I'll have a new version released within a week.

Sadly it won't be able to work with images that were generated after saving/loading them through `yara save` and `yara load`. That's because it needs the workflow data to be embedded into the .png file, but that isn't available through the ComfyUI API, so all saved/loaded prompts lose the workflow data.

I think I might only have it be possible to un-mute KSampler and KSampler Advanced nodes. I'd like to have it work with any node, but doing so might require a lot of manual/hardcoded data (related to [ComfyUI #2275](https://github.com/comfyanonymous/ComfyUI/issues/2275)). I'm struggling to think of a situation where it would be helpful to un-mute and regenerate any node other than a sampler, so I might save some effort and just limit this functionality to those two nodes (perhaps VAEDecode or SaveImage as well).

Also, are you on Linux? I'm very lazy and only 9% of downloads were for the Linux version, so if you're on Windows I'll probably just skip over making sure the feature works on Linux.

**Comment by Satellile** [comment]
Just added this in yara v1.0.0 through `yara regen`.

It still needs workflow metadata to function, but Yara now automatically embeds workflow data into images after generating them (either with `regen` or `load`).

-------------

To use it, you have to set custom titles for your nodes (in ComfyUI, right click => "Set Title"). If you want the node to be unmuted, modify the node title to include the command "!yara_unmute". You can also mute nodes with "!yara_mute", or replace the node with a LoadImage node (loading in the original image) with "!yara_load_here".

"!yara_unmute" only works on Sampler nodes, and "!yara_load_here" only works on nodes outputting `IMAGE`.

Once you generate the image, move it to the regen folder (by default, Yara tries to look in `ComfyUI/output/regen`, but you can customize the folder location in the config). Run `yara regen` to regenerate all the images there, with the nodes modified as specified by the commands.

--------------

Here's an example for a 2-pass workflow. Before you generate anything, here's what my workflow looked like, with the commands in the node titles:

![image](https://github.com/Satellile/yara/assets/118775491/f696a53f-5be8-4b4c-8fa4-468c6528913f)

Then, I generate the image, move it to my `regen` folder, and run `yara regen`. A new image is generated, with the same workflow, but the following changes:

![image](https://github.com/Satellile/yara/assets/118775491/758d6c6d-a327-475f-ac2e-3685386e6aca)


Note that I'm loading the original image instead of regenerating it with the first-pass sampler, to save time.

**Comment by charliebrown777** [comment]
It looks great! I will need some time to have my PC to test it. But I'll let you know if there is any problem. Thank you in advance.

**Comment by charliebrown777** [comment]
![image](https://github.com/Satellile/yara/assets/36913431/9c1059cc-7562-403e-a4b4-6805141e9c4c)
I tried this function today but returned with this error. Pls let me know what's wrong and how to solve?
